##### BEGIN image.base/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS wrapper
FROM vcwebio/conteco.controlplane.base AS base
##### END image.base/Dockerfile/image-header #####

##### BEGIN image.base/Dockerfile/conteco #####
COPY --from=wrapper /conteco/ /conteco/
ENTRYPOINT ["/conteco/bin/image/wrapper/entrypoint"]
##### END image.base/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
ENV CONTECO_ENTRYPOINT "/etc/confluent/docker/run"
##### END image/Dockerfile/build-instructions #####

##### BEGIN image.base/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="zookeeper" \
    CONTECO_NAME="base" \
    CONTECO_TAG="6.0.0" \
    CONTECO_BASE="controlplane.base" \
    CONTECO_BUILD="image-base"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="zookeeper" \
      io.vcweb.name="base" \
      io.vcweb.tag="6.0.0" \
      io.vcweb.base="controlplane.base" \
      io.vcweb.build="image-base" \
      io.vcweb.label="zookeeper.base - ContEco" \
      io.vcweb.description="Confluent Zookeeper base image, using default configuration." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.zookeeper.base --help"
##### END image.base/Dockerfile/env-labels-footer #####
