---
version: '3'
services:

# START SERVICE zookeeper.base
  zookeeper:
    image: ${CONTECO_REGISTRY}confluentinc/cp-zookeeper:6.0.0 
    environment: ['ZOOKEEPER_CLIENT_PORT=2181','ZOOKEEPER_TICK_TIME=2000']
    command: []
    volumes: ['${CONTECO_STACKPREFIX}_zookeeper_secrets_volume:/etc/zookeeper/secrets','${CONTECO_STACKPREFIX}_zookeeper_data_volume:/var/lib/zookeeper/data','${CONTECO_STACKPREFIX}_zookeeper_log_volume:/var/lib/zookeeper/log']
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${CONTECO_DC_ZOOKEEPER_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${CONTECO_DC_ZOOKEEPER_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${CONTECO_DC_ZOOKEEPER_COMPOSE_EXTENSIONS}
# END SERVICE zookeeper.base

networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${CONTECO_STACKPREFIX}_zookeeper_secrets_volume: { external: true },${CONTECO_STACKPREFIX}_zookeeper_data_volume: { external: true },${CONTECO_STACKPREFIX}_zookeeper_log_volume: { external: true }}
${CONTECO_DC_GLOBAL_COMPOSE_EXTENSIONS}
