---
version: '3'
services:

# START SERVICE zookeeper.base
  zookeeper:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.zookeeper.base:5.4.0
    environment: ['ZOOKEEPER_CLIENT_PORT=2181','ZOOKEEPER_TICK_TIME=2000']
    command: []
    volumes: ['${CONTECO_STACKPREFIX}_zookeeper_secrets_volume:/etc/zookeeper/secrets','${CONTECO_STACKPREFIX}_zookeeper_data_volume:/var/lib/zookeeper/data','${CONTECO_STACKPREFIX}_zookeeper_log_volume:/var/lib/zookeeper/log']
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      replicas: ${CONTECO_DC_ZOOKEEPER_DEPLOY_REPLICAS}
      resources:
        limits:
          cpus: '${CONTECO_DC_ZOOKEEPER_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_ZOOKEEPER_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_ZOOKEEPER_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_ZOOKEEPER_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${CONTECO_DC_ZOOKEEPER_DEPLOY_PLACEMENT_CONSTRAINTS}]
      labels: [${CONTECO_DC_ZOOKEEPER_DEPLOY_LABELS}]
    labels: [${CONTECO_DC_ZOOKEEPER_LABELS}]
# END SERVICE zookeeper.base

volumes: {${CONTECO_STACKPREFIX}_zookeeper_secrets_volume: { external: true },${CONTECO_STACKPREFIX}_zookeeper_data_volume: { external: true },${CONTECO_STACKPREFIX}_zookeeper_log_volume: { external: true }}
networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
