---
version: '3'
services:

# START SERVICE zookeeper.base
  zookeeper:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.zookeeper.base:5.4.0
    environment: ['ZOOKEEPER_CLIENT_PORT=2181','ZOOKEEPER_TICK_TIME=2000']
    command: []
    volumes: ['${CONTECO_STACKPREFIX}_zookeeper_volume:/var/lib/zookeeper/data']
    ports: []
    networks: [${CONTECO_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${CONTECO_DC_ZOOKEEPER_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_ZOOKEEPER_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_ZOOKEEPER_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_ZOOKEEPER_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: [${CONTECO_DC_ZOOKEEPER_DEPLOY_LABELS}]
# END SERVICE zookeeper.base

volumes: {${CONTECO_STACKPREFIX}_zookeeper_volume: { external: true }}
networks: {${CONTECO_NETWORKLOCAL}_overlay: { external: true }}
