#!/usr/bin/env bash
(
    . executionplane-invoke "$0 $@"
	if [[ $# -gt 1 ]] ; then
		rootPath="${CONTECO_PWD}/${BASH_ARGV[0]}"
	else
		rootPath="${CONTECO_PWD}/$1"
	fi
	deployPath="$rootPath/conteco/assets/${CONTECO_TYPE}/${CONTECO_NAME}/deploy"
	. $deployPath/environment

	if [[ "$1" == "deploy" ]] ; then
		config-deploy-generate-docker-compose-yml $deployPath
	fi
    executionplane-complete
)
