---
version: '3'
services:

# START SERVICE zookeeper.base
  zookeeper:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM}/${CONTECO_ECOSYSTEM}.zookeeper.base:5.2.3
    environment: [${CONTECO_DC_ZOOKEEPER_BASE_ENVIRONMENT}] 
    command: [${CONTECO_DC_ZOOKEEPER_BASE_COMMAND}]
    volumes: [${CONTECO_DC_ZOOKEEPER_BASE_VOLUMES}]
    ports: [${CONTECO_DC_ZOOKEEPER_BASE_PORTS}]
    networks: [${CONTECO_DC_ZOOKEEPER_BASE_NETWORKS}]
    deploy:
      mode: ${CONTECO_DC_ZOOKEEPER_BASE_DEPLOY_MODE}
      resources: 
        limits: 
          cpus: '${CONTECO_DC_ZOOKEEPER_BASE_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONTECO_DC_ZOOKEEPER_BASE_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONTECO_DC_ZOOKEEPER_BASE_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONTECO_DC_ZOOKEEPER_BASE_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
# END SERVICE zookeeper.base

volumes: {${CONTECO_DC_GLOBAL_VOLUMES}}
networks: {${CONTECO_DC_GLOBAL_NETWORKS}}
